/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  V2Api,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { TicketmasterCustom } from "./client-custom";

export class Ticketmaster extends TicketmasterCustom {
  readonly v2: V2Api;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.v2 = new V2Api(configuration);
  }

}
