/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Additional information for people who experience disabilities
 * @export
 * @interface Accessibility
 */
export interface Accessibility {
    /**
     * Accessibility\'s information
     * @type {string}
     * @memberof Accessibility
     */
    'info'?: string;
}

