/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Event\'s Access Date
 * @export
 * @interface AccessDates
 */
export interface AccessDates {
    /**
     * Boolean flag to indicate whether or not the access end date is approximated
     * @type {boolean}
     * @memberof AccessDates
     */
    'endApproximate'?: boolean;
    /**
     * Event\'s end access time
     * @type {string}
     * @memberof AccessDates
     */
    'endDateTime'?: string;
    /**
     * Boolean flag to indicate whether or not the access start date is approximated
     * @type {boolean}
     * @memberof AccessDates
     */
    'startApproximate'?: boolean;
    /**
     * Event\'s start access time
     * @type {string}
     * @memberof AccessDates
     */
    'startDateTime'?: string;
}

