/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Address
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * Address first line
     * @type {string}
     * @memberof Address
     */
    'line1'?: string;
    /**
     * Address second line
     * @type {string}
     * @memberof Address
     */
    'line2'?: string;
    /**
     * Address third line
     * @type {string}
     * @memberof Address
     */
    'line3'?: string;
}

