/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Attribution
 * @export
 * @interface Attribution
 */
export interface Attribution {
    /**
     * LicenceName
     * @type {string}
     * @memberof Attribution
     */
    'licenceName'?: string;
    /**
     * LicenceUrl
     * @type {string}
     * @memberof Attribution
     */
    'licenceUrl'?: string;
    /**
     * SourceName
     * @type {string}
     * @memberof Attribution
     */
    'sourceName'?: string;
    /**
     * SourceUrl
     * @type {string}
     * @memberof Attribution
     */
    'sourceUrl'?: string;
}

