/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Classification } from './classification';
import { ExternalLink } from './external-link';
import { Image } from './image';

/**
 * Attraction
 * @export
 * @interface Attraction
 */
export interface Attraction {
    /**
     * Description\'s of the entity
     * @type {string}
     * @memberof Attraction
     */
    'description'?: string;
    /**
     * Additional information of the entity
     * @type {string}
     * @memberof Attraction
     */
    'additionalInfo'?: string;
    /**
     * Attraction\'s classifications
     * @type {Array<Classification>}
     * @memberof Attraction
     */
    'classifications'?: Array<Classification>;
    /**
     * List of external links
     * @type {{ [key: string]: Array<ExternalLink>; }}
     * @memberof Attraction
     */
    'externalLinks'?: { [key: string]: Array<ExternalLink>; };
    /**
     * Unique id of the entity in the discovery API
     * @type {string}
     * @memberof Attraction
     */
    'id': string;
    /**
     * Images of the entity
     * @type {Set<Image>}
     * @memberof Attraction
     */
    'images'?: Set<Image>;
    /**
     * Locale in which the content is returned
     * @type {string}
     * @memberof Attraction
     */
    'locale'?: string;
    /**
     * Name of the entity
     * @type {string}
     * @memberof Attraction
     */
    'name'?: string;
    /**
     * Indicate if this is a test entity, by default test entities won\'t appear in discovery API
     * @type {boolean}
     * @memberof Attraction
     */
    'test'?: boolean;
    /**
     * Type of the entity
     * @type {string}
     * @memberof Attraction
     */
    'type': AttractionTypeEnum;
    /**
     * number of upcoming events
     * @type {{ [key: string]: number; }}
     * @memberof Attraction
     */
    'upcomingEvents'?: { [key: string]: number; };
    /**
     * URL of a web site detail page of the entity
     * @type {string}
     * @memberof Attraction
     */
    'url'?: string;
}

type AttractionTypeEnum = 'event' | 'venue' | 'attraction'


