/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Attribution } from './attribution';

/**
 * Attributions
 * @export
 * @interface Attributions
 */
export interface Attributions {
    /**
     * 
     * @type {Attribution}
     * @memberof Attributions
     */
    'description'?: Attribution;
    /**
     * Attribution descriptions - multi-lingual fields
     * @type {{ [key: string]: Attribution; }}
     * @memberof Attributions
     */
    'descriptions'?: { [key: string]: Attribution; };
}

