/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * City
 * @export
 * @interface City
 */
export interface City {
    /**
     * Name of the entity
     * @type {string}
     * @memberof City
     */
    'name'?: string;
}

