/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Level } from './level';
import { Segment } from './segment';

/**
 * Classification
 * @export
 * @interface Classification
 */
export interface Classification {
    /**
     * 
     * @type {Level}
     * @memberof Classification
     */
    'genre'?: Level;
    /**
     * True if this is the entity\'s primary classification
     * @type {boolean}
     * @memberof Classification
     */
    'primary'?: boolean;
    /**
     * 
     * @type {Segment}
     * @memberof Classification
     */
    'segment'?: Segment;
    /**
     * 
     * @type {Level}
     * @memberof Classification
     */
    'subGenre'?: Level;
    /**
     * 
     * @type {Level}
     * @memberof Classification
     */
    'subType'?: Level;
    /**
     * 
     * @type {Level}
     * @memberof Classification
     */
    'type'?: Level;
}

