/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Country
 * @export
 * @interface Country
 */
export interface Country {
    /**
     * Country code (ISO 3166)
     * @type {string}
     * @memberof Country
     */
    'countryCode'?: string;
    /**
     * Name of the entity
     * @type {string}
     * @memberof Country
     */
    'name'?: string;
}

