/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DurationFieldType } from './duration-field-type';

/**
 * 
 * @export
 * @interface DateTimeFieldType
 */
export interface DateTimeFieldType {
    /**
     * 
     * @type {DurationFieldType}
     * @memberof DateTimeFieldType
     */
    'durationType'?: DurationFieldType;
    /**
     * 
     * @type {string}
     * @memberof DateTimeFieldType
     */
    'name'?: string;
    /**
     * 
     * @type {DurationFieldType}
     * @memberof DateTimeFieldType
     */
    'rangeDurationType'?: DurationFieldType;
}

