/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DateTimeFieldType } from './date-time-field-type';
import { DurationField } from './duration-field';

/**
 * 
 * @export
 * @interface DateTimeField
 */
export interface DateTimeField {
    /**
     * 
     * @type {DurationField}
     * @memberof DateTimeField
     */
    'durationField'?: DurationField;
    /**
     * 
     * @type {DurationField}
     * @memberof DateTimeField
     */
    'leapDurationField'?: DurationField;
    /**
     * 
     * @type {boolean}
     * @memberof DateTimeField
     */
    'lenient'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof DateTimeField
     */
    'maximumValue'?: number;
    /**
     * 
     * @type {number}
     * @memberof DateTimeField
     */
    'minimumValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof DateTimeField
     */
    'name'?: string;
    /**
     * 
     * @type {DurationField}
     * @memberof DateTimeField
     */
    'rangeDurationField'?: DurationField;
    /**
     * 
     * @type {boolean}
     * @memberof DateTimeField
     */
    'supported'?: boolean;
    /**
     * 
     * @type {DateTimeFieldType}
     * @memberof DateTimeField
     */
    'type'?: DateTimeFieldType;
}

