/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DurationFieldType } from './duration-field-type';

/**
 * 
 * @export
 * @interface DurationField
 */
export interface DurationField {
    /**
     * 
     * @type {string}
     * @memberof DurationField
     */
    'name'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof DurationField
     */
    'precise'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof DurationField
     */
    'supported'?: boolean;
    /**
     * 
     * @type {DurationFieldType}
     * @memberof DurationField
     */
    'type'?: DurationFieldType;
    /**
     * 
     * @type {number}
     * @memberof DurationField
     */
    'unitMillis'?: number;
}

