/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LocalTime } from './local-time';

/**
 * Event\'s End Dates
 * @export
 * @interface EndDates
 */
export interface EndDates {
    /**
     * Boolean flag to indicate whether or not the end date is approximated
     * @type {boolean}
     * @memberof EndDates
     */
    'approximate'?: boolean;
    /**
     * The event end date time
     * @type {string}
     * @memberof EndDates
     */
    'dateTime'?: string;
    /**
     * The event end date in local date
     * @type {string}
     * @memberof EndDates
     */
    'localDate'?: string;
    /**
     * 
     * @type {LocalTime}
     * @memberof EndDates
     */
    'localTime'?: LocalTime;
    /**
     * Boolean flag to indicate whether or not the event end time has no specific time
     * @type {boolean}
     * @memberof EndDates
     */
    'noSpecificTime'?: boolean;
}

