/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface EntityChanges
 */
export interface EntityChanges {
    /**
     * 
     * @type {Set<string>}
     * @memberof EntityChanges
     */
    'changes'?: Set<string>;
    /**
     * 
     * @type {boolean}
     * @memberof EntityChanges
     */
    'newlyCreated'?: boolean;
}

