/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Event\'s Status
 * @export
 * @interface EventStatus
 */
export interface EventStatus {
    /**
     * The event\'s status code
     * @type {string}
     * @memberof EventStatus
     */
    'code'?: EventStatusCodeEnum;
}

type EventStatusCodeEnum = 'onsale' | 'offsale' | 'canceled' | 'postponed' | 'rescheduled'


