/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * ExternalLink
 * @export
 * @interface ExternalLink
 */
export interface ExternalLink {
    /**
     * An external link id is the unique identifier of a resource on a different domain or api
     * @type {string}
     * @memberof ExternalLink
     */
    'id'?: string;
    /**
     * An external link url is a url that goes to a different domain or api
     * @type {string}
     * @memberof ExternalLink
     */
    'url'?: string;
}

