/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Secondary Genre
 * @export
 * @interface Genre
 */
export interface Genre {
    /**
     * The ID of the classification\'s level
     * @type {string}
     * @memberof Genre
     */
    'id'?: string;
    /**
     * The Name of the classification\'s level
     * @type {string}
     * @memberof Genre
     */
    'name'?: string;
}

