/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Geometry } from './geometry';

/**
 * 
 * @export
 * @interface GeocodeExtension
 */
export interface GeocodeExtension {
    /**
     * 
     * @type {string}
     * @memberof GeocodeExtension
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeocodeExtension
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeocodeExtension
     */
    'county'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeocodeExtension
     */
    'formattedAddress'?: string;
    /**
     * 
     * @type {Geometry}
     * @memberof GeocodeExtension
     */
    'geometry'?: Geometry;
    /**
     * 
     * @type {string}
     * @memberof GeocodeExtension
     */
    'postalCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeocodeExtension
     */
    'route'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeocodeExtension
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeocodeExtension
     */
    'streetNumber'?: string;
}

