/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Image
 * @export
 * @interface Image
 */
export interface Image {
    /**
     * Attribution of the image
     * @type {string}
     * @memberof Image
     */
    'attribution'?: string;
    /**
     * true if the image is not the event\'s image but a fallbak image
     * @type {boolean}
     * @memberof Image
     */
    'fallback'?: boolean;
    /**
     * Height of the image
     * @type {number}
     * @memberof Image
     */
    'height'?: number;
    /**
     * Aspect ratio of the image
     * @type {string}
     * @memberof Image
     */
    'ratio'?: ImageRatioEnum;
    /**
     * Public URL of the image
     * @type {string}
     * @memberof Image
     */
    'url'?: string;
    /**
     * Width of the image
     * @type {number}
     * @memberof Image
     */
    'width'?: number;
}

type ImageRatioEnum = '169' | '32' | '43'


