/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Level
 */
export interface Level {
    /**
     * The ID of the classification\'s level
     * @type {string}
     * @memberof Level
     */
    'id'?: string;
    /**
     * The Name of the classification\'s level
     * @type {string}
     * @memberof Level
     */
    'name'?: string;
}

