/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Location
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * Latitude
     * @type {number}
     * @memberof Location
     */
    'latitude'?: number;
    /**
     * Longitude
     * @type {number}
     * @memberof Location
     */
    'longitude'?: number;
}

