/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Locale
 */
export interface Locale {
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'displayCountry'?: string;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'displayLanguage'?: string;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'displayName'?: string;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'displayScript'?: string;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'displayVariant'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof Locale
     */
    'extensionKeys'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'iso3Country'?: string;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'iso3Language'?: string;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'language'?: string;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'script'?: string;
    /**
     * 
     * @type {Set<string>}
     * @memberof Locale
     */
    'unicodeLocaleAttributes'?: Set<string>;
    /**
     * 
     * @type {Set<string>}
     * @memberof Locale
     */
    'unicodeLocaleKeys'?: Set<string>;
    /**
     * 
     * @type {string}
     * @memberof Locale
     */
    'variant'?: string;
}

