/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A selling point for tickets.
 * @export
 * @interface Outlet
 */
export interface Outlet {
    /**
     * Outlet\'s type
     * @type {string}
     * @memberof Outlet
     */
    'type'?: string;
    /**
     * Outlet\'s url
     * @type {string}
     * @memberof Outlet
     */
    'url'?: string;
}

