/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Parking
 * @export
 * @interface Parking
 */
export interface Parking {
    /**
     * Name of the entity
     * @type {string}
     * @memberof Parking
     */
    'name'?: string;
    /**
     * Url to the web page of the parking
     * @type {string}
     * @memberof Parking
     */
    'url'?: string;
}

