/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Area } from './area';
import { City } from './city';
import { Country } from './country';
import { Location } from './location';
import { State } from './state';

/**
 * Place
 * @export
 * @interface Place
 */
export interface Place {
    /**
     * 
     * @type {Address}
     * @memberof Place
     */
    'address'?: Address;
    /**
     * 
     * @type {Area}
     * @memberof Place
     */
    'area'?: Area;
    /**
     * 
     * @type {City}
     * @memberof Place
     */
    'city'?: City;
    /**
     * 
     * @type {Country}
     * @memberof Place
     */
    'country'?: Country;
    /**
     * 
     * @type {Location}
     * @memberof Place
     */
    'location'?: Location;
    /**
     * Name of the entity
     * @type {string}
     * @memberof Place
     */
    'name'?: string;
    /**
     * Postal code / zipcode of the place
     * @type {string}
     * @memberof Place
     */
    'postalCode'?: string;
    /**
     * 
     * @type {State}
     * @memberof Place
     */
    'state'?: State;
}

