/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * PriceRange
 * @export
 * @interface PriceRange
 */
export interface PriceRange {
    /**
     * Currency
     * @type {string}
     * @memberof PriceRange
     */
    'currency'?: string;
    /**
     * Maximum price
     * @type {number}
     * @memberof PriceRange
     */
    'max'?: number;
    /**
     * Minimum price
     * @type {number}
     * @memberof PriceRange
     */
    'min'?: number;
    /**
     * Type of price
     * @type {string}
     * @memberof PriceRange
     */
    'type'?: PriceRangeTypeEnum;
}

type PriceRangeTypeEnum = 'standard'


