/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Promoter
 * @export
 * @interface Promoter
 */
export interface Promoter {
    /**
     * Description of the promoter
     * @type {string}
     * @memberof Promoter
     */
    'description'?: string;
    /**
     * Id of the promoter
     * @type {string}
     * @memberof Promoter
     */
    'id'?: string;
    /**
     * Name of the promoter
     * @type {string}
     * @memberof Promoter
     */
    'name'?: string;
}

