/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Event\'s Public Onsales Dates
 * @export
 * @interface PublicSaleDates
 */
export interface PublicSaleDates {
    /**
     * Public sale\'s end dates. The date and time when the public sale will end
     * @type {string}
     * @memberof PublicSaleDates
     */
    'endDateTime'?: string;
    /**
     * Public sale\'s start dates. The date and time when the public sale will start
     * @type {string}
     * @memberof PublicSaleDates
     */
    'startDateTime'?: string;
    /**
     * True if the public sale\'s date is to be determined
     * @type {boolean}
     * @memberof PublicSaleDates
     */
    'startTBD'?: boolean;
}

