/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Seatmap
 * @export
 * @interface SeatMap
 */
export interface SeatMap {
    /**
     * Static Seatmap Url
     * @type {string}
     * @memberof SeatMap
     */
    'staticUrl'?: string;
}

