/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Twitter } from './twitter';

/**
 * Social networks data
 * @export
 * @interface Social
 */
export interface Social {
    /**
     * 
     * @type {Twitter}
     * @memberof Social
     */
    'twitter'?: Twitter;
}

