/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { LocalTime } from './local-time';

/**
 * Event\'s Start Dates
 * @export
 * @interface StartDates
 */
export interface StartDates {
    /**
     * Boolean flag to indicate whether or not the start date is TBA
     * @type {boolean}
     * @memberof StartDates
     */
    'dateTBA'?: boolean;
    /**
     * Boolean flag to indicate whether or not the start date is TBD
     * @type {boolean}
     * @memberof StartDates
     */
    'dateTBD'?: boolean;
    /**
     * The event start datetime
     * @type {string}
     * @memberof StartDates
     */
    'dateTime'?: string;
    /**
     * The event start date in local date
     * @type {string}
     * @memberof StartDates
     */
    'localDate'?: string;
    /**
     * 
     * @type {LocalTime}
     * @memberof StartDates
     */
    'localTime'?: LocalTime;
    /**
     * Boolean flag to indicate whether or not the event start time has no specific time
     * @type {boolean}
     * @memberof StartDates
     */
    'noSpecificTime'?: boolean;
    /**
     * Boolean flag to indicate whether or not the start time is TBA
     * @type {boolean}
     * @memberof StartDates
     */
    'timeTBA'?: boolean;
}

