/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DisplaySettingExtension } from './display-setting-extension';

/**
 * Event\'s extension (ticketmaster source)
 * @export
 * @interface TicketmasterEventExtensions
 */
export interface TicketmasterEventExtensions {
    /**
     * 
     * @type {DisplaySettingExtension}
     * @memberof TicketmasterEventExtensions
     */
    'displaySettings'?: DisplaySettingExtension;
}

