/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Twitter data
 * @export
 * @interface Twitter
 */
export interface Twitter {
    /**
     * Twitter handle
     * @type {string}
     * @memberof Twitter
     */
    'handle'?: TwitterHandleEnum;
    /**
     * Twitter hashtags
     * @type {Array<string>}
     * @memberof Twitter
     */
    'hashtags'?: Array<string>;
}

type TwitterHandleEnum = '@a Twitter handle'


