/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Venue general information
 * @export
 * @interface VenueGeneralInfo
 */
export interface VenueGeneralInfo {
    /**
     * Venue children rule
     * @type {string}
     * @memberof VenueGeneralInfo
     */
    'childRule'?: string;
    /**
     * Venue general rules
     * @type {string}
     * @memberof VenueGeneralInfo
     */
    'generalRule'?: string;
}

