/*
Discovery API

The Ticketmaster Discovery API allows you to search for events, attractions, or venues.

The version of the OpenAPI document: v2


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Venue box office information
 * @export
 * @interface VenueBoxOfficeInfo
 */
export interface VenueBoxOfficeInfo {
    /**
     * Venue box office accepted payment details
     * @type {string}
     * @memberof VenueBoxOfficeInfo
     */
    'acceptedPaymentDetail'?: string;
    /**
     * Venue box office opening hours
     * @type {string}
     * @memberof VenueBoxOfficeInfo
     */
    'openHoursDetail'?: string;
    /**
     * Venue box office phone number
     * @type {string}
     * @memberof VenueBoxOfficeInfo
     */
    'phoneNumberDetail'?: string;
    /**
     * Venue box office will call details
     * @type {string}
     * @memberof VenueBoxOfficeInfo
     */
    'willCallDetail'?: string;
}

